[build]
  command = "npm install && npx vite build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://swasthai-old-backend.onrender.com/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
